config/routes.rb
AmbassadorAdminTools::Application.routes.draw do
  resources :blacklists

  get 'invites/import' => 'invites#import'
  post 'invites/import' => 'invites#show_import'

  resources :invites

  get "welcome/index"
  root 'welcome#index'

  

end

app/models/blacklist.rb
class Blacklist < ActiveRecord::Base
  validates :user_id, :presence => true, :uniqueness => true
  validates :user_name, :presence => true
  before_save :already_invited?

  def already_invited?
    unless Invite.find_by user_id: self.user_id
      
      unless Invite.find_by user_name: self.user_name
        self.is_invited = "false"
        true
      else
	self.is_invited = "true"
        true
      end

    else
      self.is_invited = "true"
      true
    end
  end
  
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  validates :user_id, :presence => true, :uniqueness => true
  validates :email, :presence => true
  before_save :check_blacklist

  def check_blacklist
    unless Blacklist.find_by user_id: self.user_id
      unless Blacklist.find_by user_name: self.user_name
        true
      else
        self.errors.add(:user_name, "is blacklisted!")
        false
      end
    else
      unless Blacklist.find_by user_name: self.user_name
        true
      else
        self.errors.add(:user_name, "is blacklisted!")
        false
      end

      self.errors.add(:user_id, "ID is blacklisted!")
      false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blacklists_controller.rb
class BlacklistsController < ApplicationController
  before_action :set_blacklist, only: [:show, :edit, :update, :destroy]

  # GET /blacklists
  # GET /blacklists.json
  def index
    @blacklists = Blacklist.all
  end

  # GET /blacklists/1
  # GET /blacklists/1.json
  def show
  end

  # GET /blacklists/new
  def new
    @blacklist = Blacklist.new
  end

  # GET /blacklists/1/edit
  def edit
  end

  # POST /blacklists
  # POST /blacklists.json
  def create
    @blacklist = Blacklist.new(blacklist_params)

    respond_to do |format|
      if @blacklist.save
        format.html { redirect_to @blacklist, notice: 'Blacklist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blacklist }
      else
        format.html { render action: 'new' }
        format.json { render json: @blacklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blacklists/1
  # PATCH/PUT /blacklists/1.json
  def update
    respond_to do |format|
      if @blacklist.update(blacklist_params)
        format.html { redirect_to @blacklist, notice: 'Blacklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blacklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blacklists/1
  # DELETE /blacklists/1.json
  def destroy
    @blacklist.destroy
    respond_to do |format|
      format.html { redirect_to blacklists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blacklist
      @blacklist = Blacklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blacklist_params
      params.require(:blacklist).permit(:user_id, :user_name, :email, :reason)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  # GET /invites/1/edit
  def edit
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)
    
    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invite }
      else
        format.html { render action: 'new' }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invites/1
  # PATCH/PUT /invites/1.json
  def update
    respond_to do |format|
      if @invite.update(invite_params)
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url }
      format.json { head :no_content }
    end
  end

  # GET /invites/import
  def import
  end

  # POST /invites/import
  def show_import
    
    respond_to do |format|
      format.html { redirect_to invites_import_path, notice: 'The following users will be added if you choose to continue: ' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invite
      @invite = Invite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invite_params
      params.require(:invite).permit(:user_id, :user_name, :email, :answer)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blacklists_helper.rb
module BlacklistsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blacklists/_form.html.erb
<%= form_for(@blacklist) do |f| %>
  <% if @blacklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blacklist.errors.count, "error") %> prohibited this blacklist from being saved:</h2>

      <ul>
      <% @blacklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason, size: "40x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blacklists/edit.html.erb
<h1>Editing blacklist</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @blacklist, class: "button" %>
<%= link_to 'Back', blacklists_path, class: "button" %>

app/views/blacklists/index.html.erb
<h1>List of Blacklist Entries</h1>

<div id="BlacklistTools" class="tool_box">
  <br>
  <%= link_to 'New Blacklist Entry', new_blacklist_path, :class => "button" %>
 
  <br><br><br> 

  <%= image_tag "yellow_exclamation.png", id: "WarningImg", class: "hidden" %>
  <div id="NumberWarnings" class="hidden"></div>
  <br>
  <div id="ShowWarnButton" class="button hidden">Show Conflicts</div>
  <div id="ReshowBlacklists" class="button hidden">Show All</div>
  <br>
  <div id="ResolveButton" class="button hidden">Force Resolve(NF)</div>
</div>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>User name</th>
      <th>Email</th>
      <th colspan=3>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @blacklists.each do |blacklist| %>
      <% if blacklist.is_invited %>
        <tr class="warning_color">
      <% else %>
        <tr>
      <% end %>

        <td><%= blacklist.user_id %></td>
        <td><%= blacklist.user_name %></td>
        <td><%= blacklist.email %></td>
        <td><%= link_to 'Show', blacklist %></td>
        <td><%= link_to 'Edit', edit_blacklist_path(blacklist) %></td>
        <td><%= link_to 'Destroy', blacklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blacklists/new.html.erb
<h1>New blacklist</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', blacklists_path, class: "button" %>

app/views/blacklists/show.html.erb
<% if @blacklist.is_invited %>
  <div class="warning_color">
<% else %>
  <div>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blacklist.user_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @blacklist.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @blacklist.email %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @blacklist.reason %>
</p>

</div>
<br>
<%= link_to 'Edit', edit_blacklist_path(@blacklist), class: "button" %>
<%= link_to 'Back', blacklists_path, class: "button" %>

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
          <% if msg == "User ID is blacklisted!" %>
            <%= link_to 'View', :controller => "blacklists", :action => "show", :id => @invite.user_id %>
          <% elsif msg == "User name is blacklisted!" %>
            <%= link_to 'View', :controller => "blacklists", :action => "show", :id => Blacklist.find_by(user_name: @invite.user_name).id %>
          <% else %>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.radio_button :answer, "", :checked => true %>
    <%= label :answer, "No Response" %><br>
    <%= f.radio_button :answer, "Yes" %>
    <%= label :answer, "Yes" %><br>
    <%= f.radio_button :answer, "No" %>
    <%= label :answer, "No" %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', @invite, class: "button" %>
<%= link_to 'Back', invites_path, class: "button" %>

app/views/invites/import.html.erb
<h1>Import New Invites</h1>

<%= form_tag '/invites/import', id: "Uploader", multipart: true do %>
  <label for="import-file">Select CSV File:</label>
  <br><br>
  <%= file_field_tag "file", accept: 'text/csv', :id => "ImportUpload" %>
  <%= submit_tag %>
<% end %>
<br>
<p><%= notice %></p>

<% unless notice %>
  <div id="CalcImports" class="hidden">
<% else %>
  <div id="CaclImports">
<% end %>
<table>

<thead>
  <tr>
    <th>User ID<th>
    <th>User Name<th>
    <th>Email<th>
</thead>

<tbody>

</tbody>

</table>  
</div>

app/views/invites/index.html.erb
<h1>List of Invites</h1>

<div id="InviteTools" class="tool_box"> 
  <br>
  <%= link_to 'New Invite', new_invite_path, :class => "button" %>
  
  <br><br>
  <%= link_to 'Import Invites', invites_import_path, :class => "button" %>

  <br><br><hr>

  <h3>Filters:</h3>

  <%= radio_button_tag(:filter, "all", checked:true) %>
  <%= label_tag "Show All" %><br>
  <%= radio_button_tag(:filter, "yes") %>
  <%= label_tag "Show Yes Only" %><br>
  <%= radio_button_tag(:filter, "no" ) %>
  <%= label_tag "Show No Only" %><br><br>
  <%= radio_button_tag(:filter, "r") %>
  <%= label_tag "Show Responders Only" %><br>
  <%= radio_button_tag(:filter, "nr") %>
  <%= label_tag "Show Non-Responders Only" %><br><br>

  <hr>

  <div id="NumberSelected">
  </div>

  <br>

  <div id="SelectShownButton" class="button">Select All Shown</div>

  <br>

  <div id="DeselectAllButton" class="button">Unselect All</div>

  <br>

  <div id="ShowSelectedButton" class="button">Show Selected</div>
  <div id="ReshowAllButton" class="button hidden">Show All</div>

  <div id="SelectionTools" class="hidden"><h3>Selection Tools:</h3></div>
  
  <div id="MakeSelectedAmbs" class="button hidden">Make Ambassadors(NF)</div>
  <br>
  <div id="AddBlacklist" class="button hidden">Add to Blacklist(NF)</div>
  <br>
  <div id="DeleteSelected" class="button hidden">Delete(NF)</div>
  

</div>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>User name</th>
      <th>Email</th>
      <th>Answer</th>
      <th colspan=3>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @invites.each do |invite| %>
      <% case invite.answer %>
      <% when "Yes" %>
        <tr class="invite ans_yes responder">
      <% when "No" %>
        <tr class="invite ans_no responder">
      <% else %>
        <tr class="invite ans_nr">
      <% end %>

        
        <td><%= invite.user_id %></td>
        <td><%= invite.user_name %></td>
        <td><%= invite.email %></td>
        <td><%= invite.answer %></td>
        <td><%= link_to 'Show', invite %></td>
        <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
        <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= check_box_tag "selected_ids[]", invite.id, false, :id => "selected_ids_#{invite.id}", :class => "selectable" %></td> 

      </tr>
    <% end %>
  </tbody>
</table>

app/views/invites/new.html.erb
<h1>New invite</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', invites_path, class: "button" %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<div class="invite_stats"><strong>Stats:</strong>
  <br>Created At:
  <%= @invite.created_at %>
  <br>Updated At: 
  <%= @invite.updated_at %>
  <br>Number of Reminders Sent:
  <%= @invite.reminders %>
</div>


<p>
  <strong>User:</strong>
  <%= @invite.user_id %>
</p>

<p>
  <strong>User name:</strong>
  <%= @invite.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @invite.email %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @invite.answer %>
</p>
<div class="remind_button button">Send Reminder Email(NF)</div>
<br>
<%= link_to 'Edit', edit_invite_path(@invite), class: "button" %>
<%= link_to 'Back', invites_path, class: "button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmbassadorAdminTools</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="Background">

<div id="Header">
  <%= image_tag "logo-small.png", id: "SiteLogo" %>
  <h2>Couchsurfing Ambassador Administraion Tool</h2>
  <div id="WelcomeLink"><%= link_to 'Back to Welcome', welcome_index_path, :class => "button" %></div>
</div>

<div id="ContentBox">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<br><br>
<%= link_to 'Invited Users', invites_path, :class => "button" %>
<br><br>
<%= link_to 'Black List', blacklists_path, :class => "button" %>